### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by dmbrowne** [chentsulin/react-native-counter-ios-android#12]
Don't know what I'm doing wrong.
1. cloned the project
2. ran `npm i`
3. opened it in xcode and pressed 'run'
4. got an error in the simulator that it couldn't connect to the development server. So I looked at the terminal and I've got an error 

``` sh
Failed to build DependencyGraph: 
Naming collision detected: 
/Users/dbrowne/Sites/react-native-counter-ios-android/node_modules/remote-redux-devtools/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/dbrowne/Sites/react-native-counter-ios-android/node_modules/react-native/node_modules/fbjs/lib/warning.js

Error: 
Naming collision detected: 
/Users/dbrowne/Sites/react-native-counter-ios-android/node_modules/remote-redux-devtools/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/dbrowne/Sites/react-native-counter-ios-android/node_modules/react-native/node_modules/fbjs/lib/warning.js
```

I don't know how the other dude in the closed issue got it to run, but I can't. any suggestions?

**Comment by chentsulin** [comment]
Upgrade your npm to v3.x will get flattened dependencies. I left npm@2 for a long time, so not sure how this could happen.

**Comment by dmbrowne** [comment]
I wanted to do that but I'm a little paranoid that some modules won't work.
and if that is the case, this issue: https://github.com/npm/npm/issues/10214 says that I can't revert back to npm2 from 3 if need be.

nvm tho, thanks for getting back to me so quick, but I found another example react-native-redux repo. which seems to be working for me :)

**Comment by zalmoxisus** [comment]
Removing react manually from `/Users/dbrowne/Sites/react-native-counter-ios-android/node_modules/remote-redux-devtools/node_modules/react/` should solve that. More details in https://github.com/zalmoxisus/remote-redux-devtools/issues/11. The second solution would be to use `npm@3`. And the third to prevent Redux Devtools from installing React as suggested in https://github.com/gaearon/redux-devtools/issues/245.
