### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by phpsmarter** [chentsulin/react-native-counter-ios-android#21]
At component ,when perform the sync dispatch,use onPress={inCrement},perform the Async dispatch,using onPress={() => decrementAsync()}.What difference two dispatch?

**Comment by chentsulin** [comment]
Should be almost the same, but `onPress={() => decrementAsync()}` create a new function every render, so we should just use `onPress={decrementAsync}`

**Comment by phpsmarter** [comment]
Thanks  a lot. This is my puzzle,when change  to  **onPress={decrementAsync}**,will get some notification,which I don't know how to do.
 `2016-09-24 23:00:26.831 [warn][tid:com.facebook.react.JavaScript] Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method`stopPropagation` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by chentsulin** [comment]
Oh, my fault...If we pass action creator as event handler directly, it will received first argument event as delay... 

https://github.com/chentsulin/react-native-counter-ios-android/blob/master/src/actions/counter.js#L37

I recommend do something like below (use [stage 2 class-properties](http://babeljs.io/docs/plugins/transform-class-properties/)):

``` js
class Counter extends Component {
  decrementAsync = () => {
      this.props.decrementAsync();
  };
  render() {
     return (
         <View>
             <TouchableHighlight
                onPress={this.decrementAsync} style={styles.buttonMinus} underlayColor={colors.minus.bg}>
                 <Text style={[styles.text, styles.textColorMinus]}>Decrement async</Text>
             </TouchableHighlight>
         </View>
     );
  }
```

**Comment by phpsmarter** [comment]
Appreciate for your help.
