### ISSUE TITLE
I can't get the remote redux devtool to work

### ISSUE THREAD

**Issue by patrickpoh** [chentsulin/react-native-counter-ios-android#23]
Hi, I clone the repo and tried running the app. the app is working but the remote redux devtool doesn't seem to be working. May I know how can i fix this. thank you

**Comment by patrickpoh** [comment]
<img width="798" alt="screen shot 2017-01-21 at 6 16 54 pm" src="https://cloud.githubusercontent.com/assets/4413298/22173701/df6edf36-e005-11e6-9d3d-5bff8d3152fb.png">

**Comment by zalmoxisus** [comment]
Could you please try [http://remotedev.io/local/](http://remotedev.io/local/)? Chrome app is a bit outdated.

**Comment by patrickpoh** [comment]
@zalmoxisus hi! I tried that but it still show me that it is not working. 

I tried the following steps,

1. Run the app
2. try http://remotedev.io/local/
3. http://remotedev.io/local/ not showing anything so i refresh it.
4. Still showing state is undefined.

May i know what is the right steps?

**Comment by zalmoxisus** [comment]
@patrickpoh, I just tried it on android emulator and it works well according to your steps.

Maybe your firewall restricts websockets? Note that by default all the messaging is via external server (`remotedev.io`). You can check that the connection is established:

<img width="1268" alt="screen shot 2017-01-23 at 8 47 37 pm" src="https://cloud.githubusercontent.com/assets/7957859/22217854/4c7a5f76-e1ad-11e6-9708-86af950f1024.png">

**Comment by patrickpoh** [comment]
![screen shot 2017-01-24 at 1 43 49 pm](https://cloud.githubusercontent.com/assets/4413298/22235591/76fd1930-e23b-11e6-8056-99cebe94eba4.png)

**Comment by patrickpoh** [comment]
state is still showing undefined :(.  It looks like the websocket has connected successfully

**Comment by zalmoxisus** [comment]
You should also look to React Native console (`⌘ + D` then `Debug JS Remotely`), there should be a log like `socket hang up`.

Also you can [try it working on the web](http://zalmoxisus.github.io/monitoring/) (just click `Start monitoring`).

**Comment by patrickpoh** [comment]
![screen shot 2017-01-25 at 2 05 28 pm](https://cloud.githubusercontent.com/assets/4413298/22279733/741f116a-e307-11e6-83e1-e0e42500efec.png)

**Comment by patrickpoh** [comment]
im not seeing any socket hang up statement. Tried the link you gave me but it doesn't work as well. Thank you for your help thus far!

**Comment by zalmoxisus** [comment]
That's weird. I changed the port to use `wss` instead of `ws`. Please try [that example](http://zalmoxisus.github.io/monitoring/)  again, and make sure to click `Start monitoring` button there.

**Comment by patrickpoh** [comment]
Woooo! it is working now for my app as well! Thanks alot!

**Comment by zalmoxisus** [comment]
Seems like it was a local firewall restriction. Will stick to secure protocol then.
